name: CI-CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd task1-java-api
          mvn clean package

      - name: Build Docker image
        run: |
          cd task1-java-api
          docker build -t kaiburr-task-api:latest .

      # Optional: Run tests
      - name: Run tests
        run: |
          cd task1-java-api
          mvn test

      # Optional: Save build artifacts
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: task-management-api-jar
          path: task1-java-api/target/task-management-api-1.0.0.jar
